//-----------------------------
//COMP 249/Winter 2016
//Date: Thursday January 21, 2016
//Lab: 1
//Lab Section: PI-X
//Your name: Shiqi Lu
//Student ID: 40003741
//-----------------------------
public class Airplane {

	private int flightNum;				// flight number
	private int crewSize;				// number of crew members in plane
	private String destination;			// flight destination (one word)
	private static int numOfPlanes= 0;	// keeps track of the number of Airplane objects created
	

		// b) WRITE a private int method flightNumGenerator, which will generate a flight number
		// based on the following calculation every time a new Airplane object is created.
		// (numOfPlanes + 1) * 5
		// Once the resulting value is assigned to flightNum, the static attribute numOfPlanes must be incremented by 1.
		// This method must be invoked by ALL constructors

		private int flightNumGenerator()
		{
			flightNum = (numOfPlanes + 1) * 5;
			numOfPlanes++;
			return flightNum;
		}
		

		// c) WRITE the DEFAULT CONSTRUCTOR which sets the flightNum attribute to the value
		// generated by the private method flightNumGenerator(), sets crewSize to 0 and the 
		// destination to the null string
		 
		public Airplane()
		{
			flightNumGenerator();
			crewSize=0;
			destination=null;
		}



		// d) WRITE the COPY CONSTRUCTOR which will generate a new flightNum and assign the remaining values of 
		// the new object to those of the passed object
		
		public Airplane(Airplane a)
		{
			crewSize=a.getCrewSize();
			destination=a.getDestination();
			flightNumGenerator();
		}


		// e)  WRITE a CONSTRUCTOR with 2 arguments and assign the passed values to
		// the corresponding parameters as well as generating a new flightNum.
		
		public Airplane(int c, String d)
		{
			crewSize=c;
			destination=d;
			flightNumGenerator();
		}

		
		public void setCrewSize(int c)
		{
			crewSize = c;
		}
		
		public void setDestination (String d)
		{
			destination = d;		
		}
		
		public int getCrewSize()
		{
			return crewSize;
		}
		
		public String getDestination()
		{
			return destination;
		}
		
		public int getFlightNum()
		{
			return flightNum;
		}

		
		// f) WRITE an accessor method for the static instance variable numOfPlanes
		

		public static int getNumPlanes()
		{
			return numOfPlanes;
		}
		
		
		// g) WRITE the equals method to return true if the value of the non-static attributes of the two 
		// objects being compared are the same and false otherwise.
		public boolean equals(Airplane a)
		{
			if(a.getCrewSize()==crewSize&&a.getDestination()==destination) return true;
			else return false;
		}
		
		
		
		
		
		// h) WRITE the toString() method. The format of the string returned must be:
		// Flight number: (value stored in flightNum)
		// Crew size: (value stored in crewSize) 
		// Destination: (value stored in destination)

		public String toString()
		{
			return ("Flight number: "+flightNum+"\nCrew size: "+crewSize+"\nDestination: "+destination+"\n\n");
		}
		
		
		
			
}
