//-----------------------
// To be completed
//-----------------------
// Answer questions a) to c)
// You are not to change/add anything else

public class CandyBarDriver {

public static void main(String[] args) {
		
		CandyBar bar1 = new JustChocolate("Aero", 246, 25,45);
		System.out.println(bar1);
		System.out.println("======================================");
		bar1.info();
		System.out.println("======================================");
		CandyBar bar2 = new Filled("Caramilk", 500,false,"caramel");
		System.out.println(bar2);
		System.out.println("======================================");
		bar2.info();
		System.out.println("======================================");
		ChocolatePlus bar3 = new Filled("Oh Henry", 263,true,"nougat"); 
		bar3.info();
		System.out.println("======================================");
				
		// For each of the following statements indicate WHY it is not valid
		// Give more details than the error message generated by Eclipse
		//----------------------------------------------------------------
		
		// a) WHY it is the following declaration statement not valid
		// Give more details than the error message generated by eclipse
		// CandyBar bar4 = new ChocolatePlus("Aero", 246, false);
		/*Reason:
		 * 
		 */
		
		// b) WHY it is the following declaration statement not valid
		// Give more details than the error message generated by eclipse
		// Filled bar5 = new JustChocolate("Aero", 246, 25,45);
		/* Reason: 
		 * 
		 */
	}
}

/* Output you should get
 * ---------------------
This candy bar is made with 25% cacao and weighs 45 grams
======================================
A(n) Aero has 246 calories.
This candy bar is made with 25% cacao and weighs 45 grams
======================================
Yummy!! This bar is filled with caramel

======================================
A(n) Caramilk has 500 calories.
This candy bar has no nuts
Yummy!! This bar is filled with caramel

======================================
A(n) OhHenry has 263 calories.
This candy bar has  nuts
Yummy!! This bar is filled with nougat
*/
